import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const font = localFont({
  src: "../../public/fonts/monument-grotesk.woff2",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
